from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_aboutForm(object):
    def setupUi(self, aboutForm):
        aboutForm.setObjectName("aboutForm")
        aboutForm.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        aboutForm.resize(600, 200)
        aboutForm.setMinimumSize(QtCore.QSize(600, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/main.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        aboutForm.setWindowIcon(icon)
        self.TitleLabel = QtWidgets.QLabel(aboutForm)
        self.TitleLabel.setGeometry(QtCore.QRect(60, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.VersionLabel = QtWidgets.QLabel(aboutForm)
        self.VersionLabel.setGeometry(QtCore.QRect(20, 80, 500, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VersionLabel.setFont(font)
        self.VersionLabel.setObjectName("VersionLabel")
        self.IssueLabel = QtWidgets.QLabel(aboutForm)
        self.IssueLabel.setGeometry(QtCore.QRect(20, 120, 500, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IssueLabel.setFont(font)
        self.IssueLabel.setOpenExternalLinks(True)
        self.IssueLabel.setObjectName("IssueLabel")
        self.LatestVersionLabel = QtWidgets.QLabel(aboutForm)
        self.LatestVersionLabel.setGeometry(QtCore.QRect(20, 100, 500, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LatestVersionLabel.setFont(font)
        self.LatestVersionLabel.setOpenExternalLinks(True)
        self.LatestVersionLabel.setObjectName("LatestVersionLabel")
        self.IconLabel = QtWidgets.QLabel(aboutForm)
        self.IconLabel.setGeometry(QtCore.QRect(15, 15, 40, 40))
        self.IconLabel.setText("")
        self.IconLabel.setPixmap(QtGui.QPixmap(":/icon/icon/main.ico"))
        self.IconLabel.setObjectName("IconLabel")
        self.SubTitleLabel = QtWidgets.QLabel(aboutForm)
        self.SubTitleLabel.setGeometry(QtCore.QRect(60, 40, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.SubTitleLabel.setFont(font)
        self.SubTitleLabel.setObjectName("SubTitleLabel")
        self.LicenseLabel = QtWidgets.QLabel(aboutForm)
        self.LicenseLabel.setGeometry(QtCore.QRect(20, 140, 500, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LicenseLabel.setFont(font)
        self.LicenseLabel.setOpenExternalLinks(True)
        self.LicenseLabel.setObjectName("LicenseLabel")

        self.retranslateUi(aboutForm)
        QtCore.QMetaObject.connectSlotsByName(aboutForm)

    def retranslateUi(self, aboutForm):
        _translate = QtCore.QCoreApplication.translate
        aboutForm.setWindowTitle(_translate("aboutForm", "About"))
        self.TitleLabel.setText(_translate("aboutForm", "QtComMate"))
        self.VersionLabel.setText(_translate("aboutForm", "Version: 1.0.0"))
        self.IssueLabel.setText(_translate("aboutForm", "<html><head/><body><p>Issue:&ensp;<a href=\"https://github.com/nixgnauhcuy/QtComMate/issues\"><span style=\" color:#0000ff;\">https://github.com/nixgnauhcuy/QtComMate/issues</span></a></p></body></html>"))
        self.LatestVersionLabel.setText(_translate("aboutForm", "<html><head/><body><p>Latest Version:&ensp;<a href=\"https://github.com/nixgnauhcuy/QtComMate/releases\"><span style=\" color:#0000ff;\">https://github.com/nixgnauhcuy/QtComMate/releases</span></a></p></body></html>"))
        self.SubTitleLabel.setText(_translate("aboutForm", "Simple Serial Port Tool Based on pyqt6"))
        self.LicenseLabel.setText(_translate("aboutForm", "<html><head/><body><p>License:&ensp;<a href=\"https://github.com/nixgnauhcuy/QtComMate/blob/main/LICENSE\"><span style=\" color:#0000ff;\">https://github.com/nixgnauhcuy/QtComMate/blob/main/LICENSE</span></a></p></body></html>"))
