from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(820, 550)
        mainWindow.setMinimumSize(QtCore.QSize(820, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/main.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        mainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mainLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        mainWindow.setCentralWidget(self.centralWidget)
        self.mainStatusBar = SerialStatusBar(parent=mainWindow)
        self.mainStatusBar.setObjectName("mainStatusBar")
        mainWindow.setStatusBar(self.mainStatusBar)
        self.mainMenuBar = QtWidgets.QMenuBar(parent=mainWindow)
        self.mainMenuBar.setGeometry(QtCore.QRect(0, 0, 820, 23))
        self.mainMenuBar.setObjectName("mainMenuBar")
        self.settingsMenu = QtWidgets.QMenu(parent=self.mainMenuBar)
        self.settingsMenu.setObjectName("settingsMenu")
        self.languageMenu = QtWidgets.QMenu(parent=self.settingsMenu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/translate.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.languageMenu.setIcon(icon1)
        self.languageMenu.setObjectName("languageMenu")
        self.fontMenu = QtWidgets.QMenu(parent=self.settingsMenu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/font.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fontMenu.setIcon(icon2)
        self.fontMenu.setObjectName("fontMenu")
        self.themeMenu = QtWidgets.QMenu(parent=self.settingsMenu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/theme.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.themeMenu.setIcon(icon3)
        self.themeMenu.setObjectName("themeMenu")
        self.helpMenu = QtWidgets.QMenu(parent=self.mainMenuBar)
        self.helpMenu.setObjectName("helpMenu")
        mainWindow.setMenuBar(self.mainMenuBar)
        self.enLanguageAction = QtGui.QAction(parent=mainWindow)
        self.enLanguageAction.setCheckable(True)
        self.enLanguageAction.setObjectName("enLanguageAction")
        self.cnLanguageAction = QtGui.QAction(parent=mainWindow)
        self.cnLanguageAction.setCheckable(True)
        self.cnLanguageAction.setObjectName("cnLanguageAction")
        self.tcLanguageAction = QtGui.QAction(parent=mainWindow)
        self.tcLanguageAction.setCheckable(True)
        self.tcLanguageAction.setObjectName("tcLanguageAction")
        self.fontSettingsAction = QtGui.QAction(parent=mainWindow)
        self.fontSettingsAction.setObjectName("fontSettingsAction")
        self.lightThemeAction = QtGui.QAction(parent=mainWindow)
        self.lightThemeAction.setCheckable(True)
        self.lightThemeAction.setObjectName("lightThemeAction")
        self.darkThemeAction = QtGui.QAction(parent=mainWindow)
        self.darkThemeAction.setCheckable(True)
        self.darkThemeAction.setObjectName("darkThemeAction")
        self.aboutAction = QtGui.QAction(parent=mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/about.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.aboutAction.setIcon(icon4)
        self.aboutAction.setObjectName("aboutAction")
        self.languageMenu.addAction(self.enLanguageAction)
        self.languageMenu.addAction(self.cnLanguageAction)
        self.languageMenu.addAction(self.tcLanguageAction)
        self.fontMenu.addAction(self.fontSettingsAction)
        self.themeMenu.addAction(self.lightThemeAction)
        self.themeMenu.addAction(self.darkThemeAction)
        self.settingsMenu.addAction(self.languageMenu.menuAction())
        self.settingsMenu.addAction(self.fontMenu.menuAction())
        self.settingsMenu.addAction(self.themeMenu.menuAction())
        self.helpMenu.addAction(self.aboutAction)
        self.mainMenuBar.addAction(self.settingsMenu.menuAction())
        self.mainMenuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "QtComMate"))
        self.settingsMenu.setTitle(_translate("mainWindow", "Settings"))
        self.languageMenu.setTitle(_translate("mainWindow", "Language"))
        self.fontMenu.setTitle(_translate("mainWindow", "Font"))
        self.themeMenu.setTitle(_translate("mainWindow", "Theme"))
        self.helpMenu.setTitle(_translate("mainWindow", "Help"))
        self.enLanguageAction.setText(_translate("mainWindow", "English"))
        self.cnLanguageAction.setText(_translate("mainWindow", "简体中文"))
        self.tcLanguageAction.setText(_translate("mainWindow", "繁體中文"))
        self.fontSettingsAction.setText(_translate("mainWindow", "Font Settings"))
        self.lightThemeAction.setText(_translate("mainWindow", "light"))
        self.darkThemeAction.setText(_translate("mainWindow", "dark"))
        self.aboutAction.setText(_translate("mainWindow", "About"))
from widgets.serialStatusBar import SerialStatusBar
