from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.SerialReceiveGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.SerialReceiveGroupBox.setGeometry(QtCore.QRect(5, 5, 790, 330))
        self.SerialReceiveGroupBox.setCheckable(False)
        self.SerialReceiveGroupBox.setObjectName("SerialReceiveGroupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.SerialReceiveGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 168, 300))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.SerialReceiveFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.SerialReceiveFormLayout.setContentsMargins(0, 0, 0, 0)
        self.SerialReceiveFormLayout.setObjectName("SerialReceiveFormLayout")
        self.SerialComLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.SerialComLabel.setObjectName("SerialComLabel")
        self.SerialReceiveFormLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialComLabel)
        self.SerialComboBox = SerialPort_ComBoBox(self.formLayoutWidget)
        self.SerialComboBox.setObjectName("SerialComboBox")
        self.SerialReceiveFormLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialComboBox)
        self.SerialBaudrateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.SerialBaudrateLabel.setObjectName("SerialBaudrateLabel")
        self.SerialReceiveFormLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialBaudrateLabel)
        self.SerialBaudrateComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.SerialBaudrateComboBox.setObjectName("SerialBaudrateComboBox")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialReceiveFormLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialBaudrateComboBox)
        self.SerialStopBitLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.SerialStopBitLabel.setObjectName("SerialStopBitLabel")
        self.SerialReceiveFormLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialStopBitLabel)
        self.SerialStopBitComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.SerialStopBitComboBox.setObjectName("SerialStopBitComboBox")
        self.SerialStopBitComboBox.addItem("")
        self.SerialStopBitComboBox.addItem("")
        self.SerialStopBitComboBox.addItem("")
        self.SerialReceiveFormLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialStopBitComboBox)
        self.SerialDataBitLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.SerialDataBitLabel.setObjectName("SerialDataBitLabel")
        self.SerialReceiveFormLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialDataBitLabel)
        self.SerialDataBitcomboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.SerialDataBitcomboBox.setObjectName("SerialDataBitcomboBox")
        self.SerialDataBitcomboBox.addItem("")
        self.SerialDataBitcomboBox.addItem("")
        self.SerialDataBitcomboBox.addItem("")
        self.SerialDataBitcomboBox.addItem("")
        self.SerialReceiveFormLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialDataBitcomboBox)
        self.SerialChecksumBitLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.SerialChecksumBitLabel.setObjectName("SerialChecksumBitLabel")
        self.SerialReceiveFormLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialChecksumBitLabel)
        self.SerialChecksumBitComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.SerialChecksumBitComboBox.setObjectName("SerialChecksumBitComboBox")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialReceiveFormLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialChecksumBitComboBox)
        self.SerialReceiveHexCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.SerialReceiveHexCheckBox.setObjectName("SerialReceiveHexCheckBox")
        self.SerialReceiveFormLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialReceiveHexCheckBox)
        self.SerialReceiveTimestampCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.SerialReceiveTimestampCheckBox.setObjectName("SerialReceiveTimestampCheckBox")
        self.SerialReceiveFormLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialReceiveTimestampCheckBox)
        self.SerialReceiveClearPushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.SerialReceiveClearPushButton.setObjectName("SerialReceiveClearPushButton")
        self.SerialReceiveFormLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.SerialReceiveClearPushButton)
        self.SerialConnectComPushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.SerialConnectComPushButton.setObjectName("SerialConnectComPushButton")
        self.SerialReceiveFormLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.SerialConnectComPushButton)
        self.SerialReceiveTextEdit = QtWidgets.QTextEdit(self.SerialReceiveGroupBox)
        self.SerialReceiveTextEdit.setGeometry(QtCore.QRect(190, 30, 591, 290))
        self.SerialReceiveTextEdit.setReadOnly(True)
        self.SerialReceiveTextEdit.setObjectName("SerialReceiveTextEdit")
        self.SerialSendGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.SerialSendGroupBox.setGeometry(QtCore.QRect(5, 340, 790, 211))
        self.SerialSendGroupBox.setObjectName("SerialSendGroupBox")
        self.SerialSendTextEdit = QtWidgets.QTextEdit(self.SerialSendGroupBox)
        self.SerialSendTextEdit.setGeometry(QtCore.QRect(10, 30, 641, 111))
        self.SerialSendTextEdit.setObjectName("SerialSendTextEdit")
        self.SerialSendRepeatGroupBox = QtWidgets.QGroupBox(self.SerialSendGroupBox)
        self.SerialSendRepeatGroupBox.setGeometry(QtCore.QRect(270, 150, 141, 51))
        self.SerialSendRepeatGroupBox.setObjectName("SerialSendRepeatGroupBox")
        self.SerialSendRepeatCheckBox = QtWidgets.QCheckBox(self.SerialSendRepeatGroupBox)
        self.SerialSendRepeatCheckBox.setGeometry(QtCore.QRect(10, 25, 21, 21))
        self.SerialSendRepeatCheckBox.setText("")
        self.SerialSendRepeatCheckBox.setObjectName("SerialSendRepeatCheckBox")
        self.SerialSendRepeatDurationLineEdit = QtWidgets.QLineEdit(self.SerialSendRepeatGroupBox)
        self.SerialSendRepeatDurationLineEdit.setGeometry(QtCore.QRect(35, 25, 71, 20))
        self.SerialSendRepeatDurationLineEdit.setObjectName("SerialSendRepeatDurationLineEdit")
        self.SerialSendRepeatUnitLabel = QtWidgets.QLabel(self.SerialSendRepeatGroupBox)
        self.SerialSendRepeatUnitLabel.setGeometry(QtCore.QRect(110, 23, 25, 21))
        self.SerialSendRepeatUnitLabel.setObjectName("SerialSendRepeatUnitLabel")
        self.SerialSendPushButton = QtWidgets.QPushButton(self.SerialSendGroupBox)
        self.SerialSendPushButton.setGeometry(QtCore.QRect(660, 90, 121, 21))
        self.SerialSendPushButton.setObjectName("SerialSendPushButton")
        self.SerialHardFlowControlGroupBox = QtWidgets.QGroupBox(self.SerialSendGroupBox)
        self.SerialHardFlowControlGroupBox.setGeometry(QtCore.QRect(110, 150, 151, 51))
        self.SerialHardFlowControlGroupBox.setObjectName("SerialHardFlowControlGroupBox")
        self.SerialHardFlowControlDSRDTRCheckBox = QtWidgets.QCheckBox(self.SerialHardFlowControlGroupBox)
        self.SerialHardFlowControlDSRDTRCheckBox.setGeometry(QtCore.QRect(10, 25, 71, 20))
        self.SerialHardFlowControlDSRDTRCheckBox.setObjectName("SerialHardFlowControlDSRDTRCheckBox")
        self.SerialHardFlowControlRTSCTSCheckBox = QtWidgets.QCheckBox(self.SerialHardFlowControlGroupBox)
        self.SerialHardFlowControlRTSCTSCheckBox.setGeometry(QtCore.QRect(80, 25, 61, 20))
        self.SerialHardFlowControlRTSCTSCheckBox.setObjectName("SerialHardFlowControlRTSCTSCheckBox")
        self.SerialSendLineFeedGroupBox = QtWidgets.QGroupBox(self.SerialSendGroupBox)
        self.SerialSendLineFeedGroupBox.setGeometry(QtCore.QRect(420, 150, 101, 51))
        self.SerialSendLineFeedGroupBox.setObjectName("SerialSendLineFeedGroupBox")
        self.SerialSendLineFeedComboBox = QtWidgets.QComboBox(self.SerialSendLineFeedGroupBox)
        self.SerialSendLineFeedComboBox.setGeometry(QtCore.QRect(10, 25, 81, 21))
        self.SerialSendLineFeedComboBox.setObjectName("SerialSendLineFeedComboBox")
        self.SerialSendLineFeedComboBox.addItem("")
        self.SerialSendLineFeedComboBox.addItem("")
        self.SerialSendLineFeedComboBox.addItem("")
        self.SerialSendHexCheckBox = QtWidgets.QCheckBox(self.SerialSendGroupBox)
        self.SerialSendHexCheckBox.setGeometry(QtCore.QRect(660, 30, 50, 20))
        self.SerialSendHexCheckBox.setObjectName("SerialSendHexCheckBox")
        self.SerialSoftFlowControlGroupBox = QtWidgets.QGroupBox(self.SerialSendGroupBox)
        self.SerialSoftFlowControlGroupBox.setGeometry(QtCore.QRect(10, 150, 91, 51))
        self.SerialSoftFlowControlGroupBox.setObjectName("SerialSoftFlowControlGroupBox")
        self.SerialSoftFlowControlCheckBox = QtWidgets.QCheckBox(self.SerialSoftFlowControlGroupBox)
        self.SerialSoftFlowControlCheckBox.setGeometry(QtCore.QRect(5, 25, 81, 20))
        self.SerialSoftFlowControlCheckBox.setObjectName("SerialSoftFlowControlCheckBox")
        self.SerialSendClearPushButton = QtWidgets.QPushButton(self.SerialSendGroupBox)
        self.SerialSendClearPushButton.setGeometry(QtCore.QRect(660, 120, 121, 21))
        self.SerialSendClearPushButton.setObjectName("SerialSendClearPushButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.SerialStatusBar = QtWidgets.QStatusBar(MainWindow)
        self.SerialStatusBar.setObjectName("SerialStatusBar")
        MainWindow.setStatusBar(self.SerialStatusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.MenuLanguage = QtWidgets.QMenu(self.menu)
        self.MenuLanguage.setObjectName("MenuLanguage")
        MainWindow.setMenuBar(self.menuBar)
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.CnLanguageAction = QtGui.QAction(MainWindow)
        self.CnLanguageAction.setCheckable(True)
        self.CnLanguageAction.setChecked(True)
        self.CnLanguageAction.setObjectName("CnLanguageAction")
        self.EnLanguageAction = QtGui.QAction(MainWindow)
        self.EnLanguageAction.setCheckable(True)
        self.EnLanguageAction.setEnabled(True)
        self.EnLanguageAction.setObjectName("EnLanguageAction")
        self.MenuLanguage.addAction(self.CnLanguageAction)
        self.MenuLanguage.addAction(self.EnLanguageAction)
        self.menu.addAction(self.MenuLanguage.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtComMate"))
        self.SerialReceiveGroupBox.setTitle(_translate("MainWindow", "串口接收设置"))
        self.SerialComLabel.setText(_translate("MainWindow", "COM"))
        self.SerialBaudrateLabel.setText(_translate("MainWindow", "波特率"))
        self.SerialBaudrateComboBox.setItemText(0, _translate("MainWindow", "custom"))
        self.SerialBaudrateComboBox.setItemText(1, _translate("MainWindow", "110"))
        self.SerialBaudrateComboBox.setItemText(2, _translate("MainWindow", "300"))
        self.SerialBaudrateComboBox.setItemText(3, _translate("MainWindow", "600"))
        self.SerialBaudrateComboBox.setItemText(4, _translate("MainWindow", "1200"))
        self.SerialBaudrateComboBox.setItemText(5, _translate("MainWindow", "2400"))
        self.SerialBaudrateComboBox.setItemText(6, _translate("MainWindow", "4800"))
        self.SerialBaudrateComboBox.setItemText(7, _translate("MainWindow", "9600"))
        self.SerialBaudrateComboBox.setItemText(8, _translate("MainWindow", "19200"))
        self.SerialBaudrateComboBox.setItemText(9, _translate("MainWindow", "38400"))
        self.SerialBaudrateComboBox.setItemText(10, _translate("MainWindow", "57600"))
        self.SerialBaudrateComboBox.setItemText(11, _translate("MainWindow", "76800"))
        self.SerialBaudrateComboBox.setItemText(12, _translate("MainWindow", "115200"))
        self.SerialBaudrateComboBox.setItemText(13, _translate("MainWindow", "128000"))
        self.SerialBaudrateComboBox.setItemText(14, _translate("MainWindow", "230400"))
        self.SerialBaudrateComboBox.setItemText(15, _translate("MainWindow", "256000"))
        self.SerialBaudrateComboBox.setItemText(16, _translate("MainWindow", "460800"))
        self.SerialBaudrateComboBox.setItemText(17, _translate("MainWindow", "512000"))
        self.SerialBaudrateComboBox.setItemText(18, _translate("MainWindow", "576000"))
        self.SerialBaudrateComboBox.setItemText(19, _translate("MainWindow", "921600"))
        self.SerialBaudrateComboBox.setItemText(20, _translate("MainWindow", "1000000"))
        self.SerialBaudrateComboBox.setItemText(21, _translate("MainWindow", "1500000"))
        self.SerialBaudrateComboBox.setItemText(22, _translate("MainWindow", "2000000"))
        self.SerialStopBitLabel.setText(_translate("MainWindow", "停止位"))
        self.SerialStopBitComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.SerialStopBitComboBox.setItemText(1, _translate("MainWindow", "1.5"))
        self.SerialStopBitComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.SerialDataBitLabel.setText(_translate("MainWindow", "数据位"))
        self.SerialDataBitcomboBox.setItemText(0, _translate("MainWindow", "5"))
        self.SerialDataBitcomboBox.setItemText(1, _translate("MainWindow", "6"))
        self.SerialDataBitcomboBox.setItemText(2, _translate("MainWindow", "7"))
        self.SerialDataBitcomboBox.setItemText(3, _translate("MainWindow", "8"))
        self.SerialChecksumBitLabel.setText(_translate("MainWindow", "校验位"))
        self.SerialChecksumBitComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.SerialChecksumBitComboBox.setItemText(1, _translate("MainWindow", "Even"))
        self.SerialChecksumBitComboBox.setItemText(2, _translate("MainWindow", "Odd"))
        self.SerialChecksumBitComboBox.setItemText(3, _translate("MainWindow", "Mark"))
        self.SerialChecksumBitComboBox.setItemText(4, _translate("MainWindow", "Space"))
        self.SerialReceiveHexCheckBox.setText(_translate("MainWindow", "Hex"))
        self.SerialReceiveTimestampCheckBox.setText(_translate("MainWindow", "时间戳"))
        self.SerialReceiveClearPushButton.setText(_translate("MainWindow", "清空接收区"))
        self.SerialConnectComPushButton.setText(_translate("MainWindow", "连接COM"))
        self.SerialSendGroupBox.setTitle(_translate("MainWindow", "串口发送设置"))
        self.SerialSendRepeatGroupBox.setTitle(_translate("MainWindow", "重复"))
        self.SerialSendRepeatUnitLabel.setText(_translate("MainWindow", "ms"))
        self.SerialSendPushButton.setText(_translate("MainWindow", "发送"))
        self.SerialHardFlowControlGroupBox.setTitle(_translate("MainWindow", "硬件流控"))
        self.SerialHardFlowControlDSRDTRCheckBox.setText(_translate("MainWindow", "dsr/dtr"))
        self.SerialHardFlowControlRTSCTSCheckBox.setText(_translate("MainWindow", "rts/cts"))
        self.SerialSendLineFeedGroupBox.setTitle(_translate("MainWindow", "换行"))
        self.SerialSendLineFeedComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.SerialSendLineFeedComboBox.setItemText(1, _translate("MainWindow", "/r/n"))
        self.SerialSendLineFeedComboBox.setItemText(2, _translate("MainWindow", "/n"))
        self.SerialSendHexCheckBox.setText(_translate("MainWindow", "Hex"))
        self.SerialSoftFlowControlGroupBox.setTitle(_translate("MainWindow", "软件流控"))
        self.SerialSoftFlowControlCheckBox.setText(_translate("MainWindow", "xon/xoff"))
        self.SerialSendClearPushButton.setText(_translate("MainWindow", "清除"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.MenuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.action_2.setText(_translate("MainWindow", "中文"))
        self.CnLanguageAction.setText(_translate("MainWindow", "zh-CN"))
        self.EnLanguageAction.setText(_translate("MainWindow", "en"))
from serialport_combobox import SerialPort_ComBoBox
