from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 520)
        MainWindow.setMinimumSize(QtCore.QSize(800, 520))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/main.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.SerialReceiveGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.SerialReceiveGroupBox.setCheckable(False)
        self.SerialReceiveGroupBox.setObjectName("SerialReceiveGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SerialReceiveGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SerialReceiveFormLayout = QtWidgets.QFormLayout()
        self.SerialReceiveFormLayout.setObjectName("SerialReceiveFormLayout")
        self.SerialComboBox = SerialPort_ComBoBox(self.SerialReceiveGroupBox)
        self.SerialComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.SerialComboBox.setMaximumSize(QtCore.QSize(170, 21))
        self.SerialComboBox.setObjectName("SerialComboBox")
        self.SerialReceiveFormLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.SerialComboBox)
        self.SerialBaudrateLabel = QtWidgets.QLabel(self.SerialReceiveGroupBox)
        self.SerialBaudrateLabel.setObjectName("SerialBaudrateLabel")
        self.SerialReceiveFormLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialBaudrateLabel)
        self.SerialBaudrateComboBox = QtWidgets.QComboBox(self.SerialReceiveGroupBox)
        self.SerialBaudrateComboBox.setObjectName("SerialBaudrateComboBox")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialBaudrateComboBox.addItem("")
        self.SerialReceiveFormLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialBaudrateComboBox)
        self.SerialStopBitLabel = QtWidgets.QLabel(self.SerialReceiveGroupBox)
        self.SerialStopBitLabel.setObjectName("SerialStopBitLabel")
        self.SerialReceiveFormLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialStopBitLabel)
        self.SerialStopBitComboBox = QtWidgets.QComboBox(self.SerialReceiveGroupBox)
        self.SerialStopBitComboBox.setObjectName("SerialStopBitComboBox")
        self.SerialStopBitComboBox.addItem("")
        self.SerialStopBitComboBox.addItem("")
        self.SerialStopBitComboBox.addItem("")
        self.SerialReceiveFormLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialStopBitComboBox)
        self.SerialDataBitLabel = QtWidgets.QLabel(self.SerialReceiveGroupBox)
        self.SerialDataBitLabel.setObjectName("SerialDataBitLabel")
        self.SerialReceiveFormLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialDataBitLabel)
        self.SerialDataBitcomboBox = QtWidgets.QComboBox(self.SerialReceiveGroupBox)
        self.SerialDataBitcomboBox.setObjectName("SerialDataBitcomboBox")
        self.SerialDataBitcomboBox.addItem("")
        self.SerialDataBitcomboBox.addItem("")
        self.SerialDataBitcomboBox.addItem("")
        self.SerialDataBitcomboBox.addItem("")
        self.SerialReceiveFormLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialDataBitcomboBox)
        self.SerialChecksumBitLabel = QtWidgets.QLabel(self.SerialReceiveGroupBox)
        self.SerialChecksumBitLabel.setObjectName("SerialChecksumBitLabel")
        self.SerialReceiveFormLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialChecksumBitLabel)
        self.SerialChecksumBitComboBox = QtWidgets.QComboBox(self.SerialReceiveGroupBox)
        self.SerialChecksumBitComboBox.setObjectName("SerialChecksumBitComboBox")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialChecksumBitComboBox.addItem("")
        self.SerialReceiveFormLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialChecksumBitComboBox)
        self.SerialReceiveHexCheckBox = QtWidgets.QCheckBox(self.SerialReceiveGroupBox)
        self.SerialReceiveHexCheckBox.setObjectName("SerialReceiveHexCheckBox")
        self.SerialReceiveFormLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SerialReceiveHexCheckBox)
        self.SerialReceiveTimestampCheckBox = QtWidgets.QCheckBox(self.SerialReceiveGroupBox)
        self.SerialReceiveTimestampCheckBox.setObjectName("SerialReceiveTimestampCheckBox")
        self.SerialReceiveFormLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SerialReceiveTimestampCheckBox)
        self.SerialConnectComPushButton = QtWidgets.QPushButton(self.SerialReceiveGroupBox)
        self.SerialConnectComPushButton.setObjectName("SerialConnectComPushButton")
        self.SerialReceiveFormLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.SerialConnectComPushButton)
        self.SerialReceiveClearPushButton = QtWidgets.QPushButton(self.SerialReceiveGroupBox)
        self.SerialReceiveClearPushButton.setObjectName("SerialReceiveClearPushButton")
        self.SerialReceiveFormLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.SerialReceiveClearPushButton)
        self.gridLayout_2.addLayout(self.SerialReceiveFormLayout, 0, 0, 1, 1)
        self.SerialReceivePlainTextEdit = QtWidgets.QPlainTextEdit(self.SerialReceiveGroupBox)
        self.SerialReceivePlainTextEdit.setReadOnly(True)
        self.SerialReceivePlainTextEdit.setObjectName("SerialReceivePlainTextEdit")
        self.gridLayout_2.addWidget(self.SerialReceivePlainTextEdit, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.SerialReceiveGroupBox, 0, 0, 1, 1)
        self.SerialTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.SerialTabWidget.setObjectName("SerialTabWidget")
        self.SerialTab_1 = QtWidgets.QWidget()
        self.SerialTab_1.setObjectName("SerialTab_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SerialTab_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SerialSendPlainTextEdit = QtWidgets.QPlainTextEdit(self.SerialTab_1)
        self.SerialSendPlainTextEdit.setObjectName("SerialSendPlainTextEdit")
        self.gridLayout_3.addWidget(self.SerialSendPlainTextEdit, 0, 0, 3, 4)
        self.SerialSendHexCheckBox = QtWidgets.QCheckBox(self.SerialTab_1)
        self.SerialSendHexCheckBox.setObjectName("SerialSendHexCheckBox")
        self.gridLayout_3.addWidget(self.SerialSendHexCheckBox, 0, 4, 1, 1)
        self.SerialSendPushButton = QtWidgets.QPushButton(self.SerialTab_1)
        self.SerialSendPushButton.setObjectName("SerialSendPushButton")
        self.gridLayout_3.addWidget(self.SerialSendPushButton, 1, 4, 1, 1)
        self.SerialSendClearPushButton = QtWidgets.QPushButton(self.SerialTab_1)
        self.SerialSendClearPushButton.setObjectName("SerialSendClearPushButton")
        self.gridLayout_3.addWidget(self.SerialSendClearPushButton, 2, 4, 1, 1)
        self.SerialSoftFlowControlGroupBox = QtWidgets.QGroupBox(self.SerialTab_1)
        self.SerialSoftFlowControlGroupBox.setObjectName("SerialSoftFlowControlGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SerialSoftFlowControlGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SerialSoftFlowControlCheckBox = QtWidgets.QCheckBox(self.SerialSoftFlowControlGroupBox)
        self.SerialSoftFlowControlCheckBox.setObjectName("SerialSoftFlowControlCheckBox")
        self.horizontalLayout.addWidget(self.SerialSoftFlowControlCheckBox)
        self.gridLayout_3.addWidget(self.SerialSoftFlowControlGroupBox, 3, 0, 1, 1)
        self.SerialSendRepeatGroupBox = QtWidgets.QGroupBox(self.SerialTab_1)
        self.SerialSendRepeatGroupBox.setObjectName("SerialSendRepeatGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.SerialSendRepeatGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SerialSendRepeatCheckBox = QtWidgets.QCheckBox(self.SerialSendRepeatGroupBox)
        self.SerialSendRepeatCheckBox.setText("")
        self.SerialSendRepeatCheckBox.setObjectName("SerialSendRepeatCheckBox")
        self.gridLayout_4.addWidget(self.SerialSendRepeatCheckBox, 0, 0, 1, 1)
        self.SerialSendRepeatUnitLabel = QtWidgets.QLabel(self.SerialSendRepeatGroupBox)
        self.SerialSendRepeatUnitLabel.setObjectName("SerialSendRepeatUnitLabel")
        self.gridLayout_4.addWidget(self.SerialSendRepeatUnitLabel, 0, 2, 1, 1)
        self.SerialSendRepeatDurationLineEdit = QtWidgets.QLineEdit(self.SerialSendRepeatGroupBox)
        self.SerialSendRepeatDurationLineEdit.setObjectName("SerialSendRepeatDurationLineEdit")
        self.gridLayout_4.addWidget(self.SerialSendRepeatDurationLineEdit, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.SerialSendRepeatGroupBox, 3, 2, 1, 1)
        self.SerialSendLineFeedGroupBox = QtWidgets.QGroupBox(self.SerialTab_1)
        self.SerialSendLineFeedGroupBox.setObjectName("SerialSendLineFeedGroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.SerialSendLineFeedGroupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SerialSendLineFeedComboBox = QtWidgets.QComboBox(self.SerialSendLineFeedGroupBox)
        self.SerialSendLineFeedComboBox.setObjectName("SerialSendLineFeedComboBox")
        self.SerialSendLineFeedComboBox.addItem("")
        self.SerialSendLineFeedComboBox.addItem("")
        self.SerialSendLineFeedComboBox.addItem("")
        self.SerialSendLineFeedComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.SerialSendLineFeedComboBox)
        self.gridLayout_3.addWidget(self.SerialSendLineFeedGroupBox, 3, 3, 1, 1)
        self.SerialHardFlowControlGroupBox = QtWidgets.QGroupBox(self.SerialTab_1)
        self.SerialHardFlowControlGroupBox.setObjectName("SerialHardFlowControlGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SerialHardFlowControlGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SerialHardFlowControlDSRDTRCheckBox = QtWidgets.QCheckBox(self.SerialHardFlowControlGroupBox)
        self.SerialHardFlowControlDSRDTRCheckBox.setObjectName("SerialHardFlowControlDSRDTRCheckBox")
        self.horizontalLayout_2.addWidget(self.SerialHardFlowControlDSRDTRCheckBox)
        self.SerialHardFlowControlRTSCTSCheckBox = QtWidgets.QCheckBox(self.SerialHardFlowControlGroupBox)
        self.SerialHardFlowControlRTSCTSCheckBox.setObjectName("SerialHardFlowControlRTSCTSCheckBox")
        self.horizontalLayout_2.addWidget(self.SerialHardFlowControlRTSCTSCheckBox)
        self.gridLayout_3.addWidget(self.SerialHardFlowControlGroupBox, 3, 1, 1, 1)
        self.SerialTabWidget.addTab(self.SerialTab_1, "")
        self.SerialTab_2 = QtWidgets.QWidget()
        self.SerialTab_2.setObjectName("SerialTab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SerialTab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.SerialFileSendGroupBox = QtWidgets.QGroupBox(self.SerialTab_2)
        self.SerialFileSendGroupBox.setObjectName("SerialFileSendGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.SerialFileSendGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SerialFileSendLabel = QtWidgets.QLabel(self.SerialFileSendGroupBox)
        self.SerialFileSendLabel.setObjectName("SerialFileSendLabel")
        self.horizontalLayout_4.addWidget(self.SerialFileSendLabel)
        self.SerialFileSendLineEdit = QtWidgets.QLineEdit(self.SerialFileSendGroupBox)
        self.SerialFileSendLineEdit.setReadOnly(True)
        self.SerialFileSendLineEdit.setObjectName("SerialFileSendLineEdit")
        self.horizontalLayout_4.addWidget(self.SerialFileSendLineEdit)
        self.SerialFileSelectPushButton = QtWidgets.QPushButton(self.SerialFileSendGroupBox)
        self.SerialFileSelectPushButton.setObjectName("SerialFileSelectPushButton")
        self.horizontalLayout_4.addWidget(self.SerialFileSelectPushButton)
        self.SerialFileSendPushButton = QtWidgets.QPushButton(self.SerialFileSendGroupBox)
        self.SerialFileSendPushButton.setObjectName("SerialFileSendPushButton")
        self.horizontalLayout_4.addWidget(self.SerialFileSendPushButton)
        self.gridLayout_5.addWidget(self.SerialFileSendGroupBox, 0, 1, 1, 1)
        self.SerialFileSaveGroupBox = QtWidgets.QGroupBox(self.SerialTab_2)
        self.SerialFileSaveGroupBox.setObjectName("SerialFileSaveGroupBox")
        self.gridLayout_5.addWidget(self.SerialFileSaveGroupBox, 1, 1, 1, 1)
        self.SerialTabWidget.addTab(self.SerialTab_2, "")
        self.gridLayout.addWidget(self.SerialTabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.SerialStatusBar = QtWidgets.QStatusBar(MainWindow)
        self.SerialStatusBar.setObjectName("SerialStatusBar")
        MainWindow.setStatusBar(self.SerialStatusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.MenuLanguage = QtWidgets.QMenu(self.menu)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/translate.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MenuLanguage.setIcon(icon1)
        self.MenuLanguage.setObjectName("MenuLanguage")
        self.MenuFont = QtWidgets.QMenu(self.menu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/font.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MenuFont.setIcon(icon2)
        self.MenuFont.setObjectName("MenuFont")
        self.MenuTheme = QtWidgets.QMenu(self.menu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/theme.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MenuTheme.setIcon(icon3)
        self.MenuTheme.setObjectName("MenuTheme")
        MainWindow.setMenuBar(self.menuBar)
        self.EnglishLanguageAction = QtGui.QAction(MainWindow)
        self.EnglishLanguageAction.setCheckable(True)
        self.EnglishLanguageAction.setChecked(True)
        self.EnglishLanguageAction.setObjectName("EnglishLanguageAction")
        self.SimplifiedChineseLanguageAction = QtGui.QAction(MainWindow)
        self.SimplifiedChineseLanguageAction.setCheckable(True)
        self.SimplifiedChineseLanguageAction.setObjectName("SimplifiedChineseLanguageAction")
        self.TraditionalChineseLanguageAction = QtGui.QAction(MainWindow)
        self.TraditionalChineseLanguageAction.setCheckable(True)
        self.TraditionalChineseLanguageAction.setObjectName("TraditionalChineseLanguageAction")
        self.FontSetAction = QtGui.QAction(MainWindow)
        self.FontSetAction.setObjectName("FontSetAction")
        self.LightThemeAction = QtGui.QAction(MainWindow)
        self.LightThemeAction.setCheckable(True)
        self.LightThemeAction.setObjectName("LightThemeAction")
        self.DarkThemeAction = QtGui.QAction(MainWindow)
        self.DarkThemeAction.setCheckable(True)
        self.DarkThemeAction.setObjectName("DarkThemeAction")
        self.MenuLanguage.addAction(self.EnglishLanguageAction)
        self.MenuLanguage.addAction(self.SimplifiedChineseLanguageAction)
        self.MenuLanguage.addAction(self.TraditionalChineseLanguageAction)
        self.MenuFont.addAction(self.FontSetAction)
        self.MenuTheme.addAction(self.LightThemeAction)
        self.MenuTheme.addAction(self.DarkThemeAction)
        self.menu.addAction(self.MenuLanguage.menuAction())
        self.menu.addAction(self.MenuFont.menuAction())
        self.menu.addAction(self.MenuTheme.menuAction())
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.SerialTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtComMate"))
        self.SerialReceiveGroupBox.setTitle(_translate("MainWindow", "Receive Area"))
        self.SerialBaudrateLabel.setText(_translate("MainWindow", "Baudrate"))
        self.SerialBaudrateComboBox.setItemText(0, _translate("MainWindow", "custom"))
        self.SerialBaudrateComboBox.setItemText(1, _translate("MainWindow", "110"))
        self.SerialBaudrateComboBox.setItemText(2, _translate("MainWindow", "300"))
        self.SerialBaudrateComboBox.setItemText(3, _translate("MainWindow", "600"))
        self.SerialBaudrateComboBox.setItemText(4, _translate("MainWindow", "1200"))
        self.SerialBaudrateComboBox.setItemText(5, _translate("MainWindow", "2400"))
        self.SerialBaudrateComboBox.setItemText(6, _translate("MainWindow", "4800"))
        self.SerialBaudrateComboBox.setItemText(7, _translate("MainWindow", "9600"))
        self.SerialBaudrateComboBox.setItemText(8, _translate("MainWindow", "19200"))
        self.SerialBaudrateComboBox.setItemText(9, _translate("MainWindow", "38400"))
        self.SerialBaudrateComboBox.setItemText(10, _translate("MainWindow", "57600"))
        self.SerialBaudrateComboBox.setItemText(11, _translate("MainWindow", "76800"))
        self.SerialBaudrateComboBox.setItemText(12, _translate("MainWindow", "115200"))
        self.SerialBaudrateComboBox.setItemText(13, _translate("MainWindow", "128000"))
        self.SerialBaudrateComboBox.setItemText(14, _translate("MainWindow", "230400"))
        self.SerialBaudrateComboBox.setItemText(15, _translate("MainWindow", "256000"))
        self.SerialBaudrateComboBox.setItemText(16, _translate("MainWindow", "460800"))
        self.SerialBaudrateComboBox.setItemText(17, _translate("MainWindow", "512000"))
        self.SerialBaudrateComboBox.setItemText(18, _translate("MainWindow", "576000"))
        self.SerialBaudrateComboBox.setItemText(19, _translate("MainWindow", "921600"))
        self.SerialBaudrateComboBox.setItemText(20, _translate("MainWindow", "1000000"))
        self.SerialBaudrateComboBox.setItemText(21, _translate("MainWindow", "1500000"))
        self.SerialBaudrateComboBox.setItemText(22, _translate("MainWindow", "2000000"))
        self.SerialStopBitLabel.setText(_translate("MainWindow", "Stopbit"))
        self.SerialStopBitComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.SerialStopBitComboBox.setItemText(1, _translate("MainWindow", "1.5"))
        self.SerialStopBitComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.SerialDataBitLabel.setText(_translate("MainWindow", "Databit"))
        self.SerialDataBitcomboBox.setItemText(0, _translate("MainWindow", "5"))
        self.SerialDataBitcomboBox.setItemText(1, _translate("MainWindow", "6"))
        self.SerialDataBitcomboBox.setItemText(2, _translate("MainWindow", "7"))
        self.SerialDataBitcomboBox.setItemText(3, _translate("MainWindow", "8"))
        self.SerialChecksumBitLabel.setText(_translate("MainWindow", "Checksum"))
        self.SerialChecksumBitComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.SerialChecksumBitComboBox.setItemText(1, _translate("MainWindow", "Even"))
        self.SerialChecksumBitComboBox.setItemText(2, _translate("MainWindow", "Odd"))
        self.SerialChecksumBitComboBox.setItemText(3, _translate("MainWindow", "Mark"))
        self.SerialChecksumBitComboBox.setItemText(4, _translate("MainWindow", "Space"))
        self.SerialReceiveHexCheckBox.setText(_translate("MainWindow", "Hex"))
        self.SerialReceiveTimestampCheckBox.setText(_translate("MainWindow", "Timestamp"))
        self.SerialConnectComPushButton.setText(_translate("MainWindow", "Connect"))
        self.SerialReceiveClearPushButton.setText(_translate("MainWindow", "Clear"))
        self.SerialSendHexCheckBox.setText(_translate("MainWindow", "Hex"))
        self.SerialSendPushButton.setText(_translate("MainWindow", "Send"))
        self.SerialSendClearPushButton.setText(_translate("MainWindow", "Clear"))
        self.SerialSoftFlowControlGroupBox.setTitle(_translate("MainWindow", "Software Flow Control"))
        self.SerialSoftFlowControlCheckBox.setText(_translate("MainWindow", "xon/xoff"))
        self.SerialSendRepeatGroupBox.setTitle(_translate("MainWindow", "Repeat"))
        self.SerialSendRepeatUnitLabel.setText(_translate("MainWindow", "ms"))
        self.SerialSendLineFeedGroupBox.setTitle(_translate("MainWindow", "New Line"))
        self.SerialSendLineFeedComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.SerialSendLineFeedComboBox.setItemText(1, _translate("MainWindow", "\\r\\n"))
        self.SerialSendLineFeedComboBox.setItemText(2, _translate("MainWindow", "\\n"))
        self.SerialSendLineFeedComboBox.setItemText(3, _translate("MainWindow", "\\r"))
        self.SerialHardFlowControlGroupBox.setTitle(_translate("MainWindow", "Hardware Flow Control"))
        self.SerialHardFlowControlDSRDTRCheckBox.setText(_translate("MainWindow", "dsr/dtr"))
        self.SerialHardFlowControlRTSCTSCheckBox.setText(_translate("MainWindow", "rts/cts"))
        self.SerialTabWidget.setTabText(self.SerialTabWidget.indexOf(self.SerialTab_1), _translate("MainWindow", "Send Area"))
        self.SerialFileSendGroupBox.setTitle(_translate("MainWindow", "File Send"))
        self.SerialFileSendLabel.setText(_translate("MainWindow", "File"))
        self.SerialFileSelectPushButton.setText(_translate("MainWindow", "Select"))
        self.SerialFileSendPushButton.setText(_translate("MainWindow", "Send"))
        self.SerialFileSaveGroupBox.setTitle(_translate("MainWindow", "File Save"))
        self.SerialTabWidget.setTabText(self.SerialTabWidget.indexOf(self.SerialTab_2), _translate("MainWindow", "File"))
        self.menu.setTitle(_translate("MainWindow", "Settings"))
        self.MenuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.MenuFont.setTitle(_translate("MainWindow", "Font"))
        self.MenuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.EnglishLanguageAction.setText(_translate("MainWindow", "English"))
        self.SimplifiedChineseLanguageAction.setText(_translate("MainWindow", "简体中文"))
        self.TraditionalChineseLanguageAction.setText(_translate("MainWindow", "繁體中文"))
        self.FontSetAction.setText(_translate("MainWindow", "Font Settings"))
        self.LightThemeAction.setText(_translate("MainWindow", "light"))
        self.DarkThemeAction.setText(_translate("MainWindow", "dark"))
from serialport_combobox import SerialPort_ComBoBox
